# Generated by Django 3.0.10 on 2020-11-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="code",
        ),
    ]
