# Generated by Django 3.0.10 on 2020-11-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="date",
            new_name="date_start",
        ),
        migrations.RemoveField(
            model_name="task",
            name="periodic",
        ),
        migrations.RemoveField(
            model_name="task",
            name="typeT",
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("multimedia", "Registro multimedia"),
                    ("text", "Registro texto"),
                    ("reminder", "Recordatorio"),
                ],
                default="multimedia",
                max_length=11,
                verbose_name="Tipo de tarea",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="file_path",
            field=models.CharField(max_length=50, verbose_name="Ruta archivo"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("inprogress", "En progreso"),
                    ("canceled", "Cancelada"),
                    ("finished", "Finalizada"),
                    ("expired", "Expirada"),
                ],
                default="inprogress",
                max_length=11,
                verbose_name="Estado de tarea",
            ),
        ),
    ]
