# Generated by Django 3.0.10 on 2020-11-22 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_auto_20201122_1733"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
