# Generated by Django 3.0.10 on 2020-11-23 00:22

from django.db import migrations, models
import tracing_app.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_auto_20201122_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file_path",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=tracing_app.tasks.models.task_directory_path,
            ),
        ),
    ]
