# Generated by Django 3.0.10 on 2020-10-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20201026_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('disability', models.BooleanField(default=False, verbose_name='Discapacidad')),
                ('comments', models.TextField(verbose_name='Comentarios')),
            ],
        ),
    ]
